config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :publications do
    resources :user_publications, only: [:new , :create, :index, :destroy]
  end

  resources :users, only: [:show]

end

app/models/user_publication.rb
class UserPublication < ApplicationRecord
  belongs_to :user
  belongs_to :publication
  attr_accessor :email

  before_validation :set_user

  validates :publication, :user, presence: true
  validates :publication, uniqueness: { scope: :user, message: "you've added the user already" }

  def set_user
    self.user = User.find_by_email(self.email)
  end

end

app/controllers/user_publications_controller.rb
class UserPublicationsController < ApplicationController
  # before_action :set_user_publication
  before_action :find_publication, only: [:index,:create, :destroy, :new]
  before_action :authenticate_user!

  # GET /user_publications
  def index
    @user_publications = @publication.user_publications
    authorize @publication, :edit?
  end

  # GET /user_publications/new
  def new
    @user_publication = @publication.user_publications.new
    authorize @user_publication
  end

  # POST /user_publications
  def create
    @user_publication = @publication.user_publications.new(user_publication_params)
    authorize @user_publication
    if @user_publication.save
      redirect_to publication_user_publications_path(@publication)
    else
      flash.now[:alert] = @user_publication.errors.full_messages.join(', ')
      render :new
    end
  end

  # DELETE /user_publications/1
  def destroy
    @user_publication = @publication.user_publications.find(params[:id])
    authorize @user_publication
    @user_publication.destroy
    redirect_to publication_user_publications_path(@publication)
  end

  # private
    # Use callbacks to share common setup or constraints between actions.

  def find_publication
    @publication = Publication.find(params[:publication_id])
  end

  def user_publication_params
    params.require(:user_publication).permit(:email)
  end

end

app/helpers/user_publication_helper.rb
module UserPublicationHelper
end

app/helpers/user_publications_helper.rb
module UserPublicationsHelper
end

app/views/user_publications/_form.html.haml
.container
  = form_with model: [@publication, @user_publication], data: {remote: false} do |f|
    .row.m-3.ml-4
      .form-group
        = f.label :email
        = f.email_field :email, placeholder: "email here...", required: false, class: "form-control"
        = f.submit "Add Member", class: "btn btn-success mt-3 "
      %div

app/views/user_publications/edit.html.haml
%h1 Editing user_publication

= render 'form'

= link_to 'Show', @user_publication
\|
= link_to 'Back', user_publications_path

app/views/user_publications/index.html.haml
.container
  .jumbotron.m-4.mt-5
    %h3 Publication Members

  .col
    - @user_publications.each do |record|
      .row
        %ul
          %li
            #{link_to record.user.full_name,record.user}
            #{link_to 'Delete', publication_user_publication_path(publication_id: @publication.id, id: record.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-dark"}

    .row
      =link_to 'Add Members',new_publication_user_publication_path(@publication.id), class:"btn btn-info ml-2 mt-4"
%br

app/views/user_publications/new.html.haml
.container
  .jumbotron.m-4.mt-2
    %h3 Add members to #{@publication.title}






= render 'form'

-# = link_to 'Back', user_publications_path

app/views/user_publications/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_user_publication_path(@user_publication)
\|
= link_to 'Back', user_publications_path