config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :publications do
    resources :user_publications, only: [:new , :create, :index, :destroy]
  end

  resources :users, only: [:show]

end

app/models/publication.rb
class Publication < ApplicationRecord
  paginates_per 6
  has_many :user_publications
  has_many :users, through: :user_publications
  has_many :articles

  validates :title, uniqueness: true, presence: true
  validates :description, presence: true
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized

  # GET /publications
  def index
    @publications = Publication.all.page(params[:page])
    authorize Publication
  end

  # GET /publications/1
  def show
    authorize @publication
  end

  # GET /publications/new
  def new
    @publication = Publication.new
    authorize @publication
  end



  # POST /publications
  def create
    @publication = Publication.new(publication_params)
    authorize @publication
    if @publication.save
      UserPublication.create(email: current_user.email, publication_id: @publication.id)
      redirect_to publication_path(@publication)
    else
      render :new
    end
  end

    # GET /publications/1/edit
  def edit
    authorize @publication
  end


  # PATCH/PUT /publications/1
  def update
    authorize @publication
    if @publication.update(publication_params)
      redirect_to publication_path(@publication)
    else
      render :edit
    end
  end

  # DELETE /publications/1
  def destroy
    authorize @publication

    @publication.destroy
    redirect_to publications_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:title, :description)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper

  

end

app/views/publications/_form.html.haml
.container
  .jumbotron.m-4.mt-2
    %h1 Create a publication
  = form_with model: @publication, data: {remote: false} do |f|
    .row
      .col-md-6.offset-md-3
        -if !@publication.errors.full_messages.empty?
          .alert.alert-danger{:role => "alert"}
            = @publication.errors.full_messages.join(" ")
    .row
      .col-md-6.offset-md-3
        .form-group
          = f.label :title
          = f.text_field :title, placeholder: "title here...", required: false, class: "form-control"
        .form-group
          = f.label :description
          = f.text_area :description ,placeholder: "give description here", required: false, class: "form-control"
        %div
          = link_to 'Back', publications_path , class: "btn btn-light"
          = f.submit "Create", class: "btn btn-success"

app/views/publications/edit.html.haml
.container

  = render 'form'

  = link_to 'Show', @publication
  

app/views/publications/index.html.haml
.container
  .jumbotron.mt-5
    %h1 List of publications
    =link_to 'Create a new Publication', new_publication_path, class:'btn btn-primary mt-4'

  .row
    - @publications.each do |publication|
      .col-sm-12.col-lg-4.mb-4
        .card.h-100
          .card-body
            %h5.card-title
              = link_to publication.title, publication
            %p.card-text #{truncate(publication.description, length: 200 ,omission: '... (continued)')}
            = link_to "Read more", publication, class: 'btn btn-outline-primary btn-sm'
          .card-footer
            %small.text-muted #{time_ago_in_words(publication.created_at)} ago

    .row
      .col.mt-5
        = paginate @publications, theme: 'twitter-bootstrap-4'

app/views/publications/new.html.haml
= render 'form'

 

app/views/publications/show.html.haml
.container
  .jumbotron.m-4.mt-5
    %h1= @publication.title
    %h6= @publication.description
    - if policy(@publication).edit?
      =link_to 'Edit', edit_publication_path(@publication),  class:"btn btn-dark ml-2 mt-4"
      =link_to 'Destroy', publication_path(@publication.id), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-dark ml-2 mt-4"
      =link_to 'Publication Members',publication_user_publications_path(@publication.id), class:"btn btn-secondary ml-2 mt-4"
  .row.p-4
    - @publication.articles.each do |i|
      .col-md-4.p-4
        %h4= link_to i.title, i
        %p= truncate(i.body,length: 210 ,omission: '... (continued)')
        = link_to "Read more >>", i