config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :publications do
    resources :user_publications, only: [:new , :create, :index, :destroy]
  end

  resources :users, only: [:show]

end

app/models/article.rb
class Article < ApplicationRecord
  paginates_per 3

  belongs_to :user

  validates :title, :body, presence: true
  validate :word_count_validate

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :publication, optional: true

  def word_count
    body.split(" ").count
  end

  def word_count_validate
    if body != nil
      if word_count < 10
        remaining = 10 - word_count
        errors.add(:body, "is too short. You need to add #{ActionController::Base.helpers.pluralize(remaining, 'word')}.")
      end
    end
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only: [:show,:edit ,:update, :destroy]

  after_action :verify_authorized

  def index
    @articles = Article.all.order(created_at: :desc).page(params[:page])
    authorize Article
  end

  def new
    @article = Article.new
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    authorize @article

    if @article.save
      ArticleMailer.with(article: @article).new_article_email.deliver_later
      flash[:success] = "Thank you for submitting an article. We'll get back to you soon"
      redirect_to @article
    else
      flash.now[:alert] = @article.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
    authorize @article

    @insight = ArticleInsightService.new(@article.body)
    @comment = @article.comments.new

    if user_signed_in?
      @like = @article.likes.where(user_id: current_user.id)&.first
    end

    @like ||= @article.likes.new

    @author = @article.user
  end

  def edit
    authorize @article
  end

  def update
    authorize @article

    if @article.update(article_params)
      redirect_to @article
    else
      flash.now[:alert] =  @article.errors.full_messages.join(',')
      render :edit
    end
  end

  def destroy
    authorize @article

    @article.destroy
    redirect_to root_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :publication_id)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def hello(name)
    "hello #{name}"
  end

  

  def can_delete_comment?(comment)
    user_signed_in? && (current_user.id == @article.user_id || comment.user_id == current_user.id)
  end

end

app/views/articles/_form_layout.html.haml
.container.p-5
= form_with model: @article, data: {remote: false} do |f|
  .row
    .col-md-6.offset-md-3

      - if @article.errors.full_messages.any?
        .alert.alert-danger{:role => "alert"}
          %ul
            - @article.errors.full_messages.each do |e|
              %li= e

    .col-md-6.offset-md-3


      .form-group
        = f.label :title
        = f.text_field :title, placeholder: "title here...", required: false, class: "form-control"
      .form-group
        = f.label :body
        = f.text_area :body ,placeholder: "Type your article here..",required: false, class: "form-control", rows: "10"
      - if current_user.publications.any?
        .form-group
          = f.label :publication_id
          = f.collection_select :publication_id, current_user.publications, :id, :title, {:include_blank => true}

      %div
        = f.submit class: "btn btn-success mt-2"

app/views/articles/edit.html.haml
= render "articles/form_layout"

app/views/articles/index.html.haml
.container
  .row
    .col.jumbotron.mt-5
      %h1 The Blog
      %p Read interesting articles and signup to submit some interesting articles.
      = link_to "Submit an Article", new_article_path, class:'btn btn-outline-primary'
  .row
    - @articles.each do |i|
      .col-md-4.p-2
        %h4= link_to i.title, i
        %p= truncate(i.body,length: 210 ,omission: '... (continued)')
        = link_to "Read more >>", i
  .row
    .col.mt-5
      = paginate @articles, theme: 'twitter-bootstrap-4'

app/views/articles/new.html.haml
= render "articles/form_layout"

app/views/articles/show.html.haml
.container
  .jumbotron.mt-5
    %h1= @article.title
    %h4= link_to "by #{@author.full_name}", @author
    %h5= "Reading Time : #{@insight.reading_time}"
    - if @article.publication != nil
      = "Published in:"
      = link_to @article.publication.title, @article.publication
  .row
    .col
      %h6= "Likes: #{@article.likes.count}"
      - if @like.persisted?
        = link_to "Unlike", article_like_path(@like.article, @like), method: :delete, class:"btn btn-primary"
      - else
        = form_with model: [@article, @like], data: {remote: false} do |f|
          = f.submit "Like", class: "btn btn-primary"
  .row.pt-3
    .col
      .text-justify
        = simple_format @article.body
  .row
    .col
      -if policy(@article).edit?
        = link_to "Edit Article", edit_article_path, class:"btn btn-dark"
        = link_to "Delete Article", article_path(@article.id), method: :delete, data: {confirm: 'Are you sure?'}, class:"btn btn-dark"
      %div
      .row.mt-4
        .col
          %h5 Comments
          - @article.comments.each do |i|
            - next if i.id == nil
            .card.mb-2
              .card-body
                %h5.card-title= link_to i.user.full_name, i.user
                %h6.card-subtitle.mb-2.text-muted= "#{time_ago_in_words(i.created_at)} ago"
                %p.card-text= i.comment
                - if can_delete_comment?(i)
                  = link_to "Delete", [i.article, i], method: :delete, data: {confirm: 'Are you sure?'}
      - if user_signed_in?
        = form_with model: [@article, @comment], data: {remote: false} do |f|
          .row
            .col.mt-3
              .form-group
                = f.text_area :comment, placeholder: "comment here",required: true, class: "form-control"
              %div
                = f.submit class: "btn btn-success"
      - else
        Please
        \#{link_to "sign in", user_session_path} or
        \#{link_to "register", new_user_registration_path}
        to comment